name: FralusIntroniseur
description: Insertion d'une intro dans une rom gba
homepage: https://www.fralacticus.fr

environment:
  sdk: '>=2.14.4 <3.0.0'

dev_dependencies:
  build_runner: ^2.1.10
  build_web_compilers: ^3.2.3


